# Deployment tasks
- id: configure_cinder_solidfire
  role: ['primary-controller', 'controller']
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/controller.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360
