- id: solidfire_hiera_override
  type: puppet
  version: 3.0.0
  groups: [primary-controller]
  requires: [hiera]
  required_for: [create-cinder-types]
  parameters:
    puppet_manifest: puppet/manifests/hiera_override.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 360

- id: solidfire_cinder_controller
  type: puppet
  version: 3.0.0
  role: [primary-controller, controller]
  requires: [openstack-cinder]
  required_for: [deploy_end]
  condition:
    yaql_exp: >
      $.storage.volumes_ceph and
      changedAny($.cinder_solidfire, $.network_scheme, $.cinder, $.network_metadata.vips,
      $.get('cinder_volume_group'), $.storage, $.ceilometer, $.sahara,
      $.rabbit, $.get('region', 'RegionOne'), $.get('use_ssl'),
      ('primary-controller' in $.roles), $.get('proxy_port'),
      $.get('kombu_compression'), $.get('keystone_endpoint'),
      $.get('glance_endpoint'), $.get('glance_api_servers'),
      $.get('use_syslog'), $.get('use_stderr'), $.get('verbose'), $.debug,
      $.network_metadata.nodes.values().where(
        $.node_roles.any($.matches('controller'))).network_roles.select(
          $.get('mgmt/messaging')),
      $.get('amqp_hosts'), $.get('syslog_log_facility_cinder'),
      $.get('cinder_rate_limits'),
      $.configuration.get('cinder_api_paste_ini'), $.configuration.get('cinder'))
  parameters:
    puppet_manifest: puppet/manifests/site.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360

# For LCM inherit condition from top-role-cinder
# otherwise enabled_backends will be overwritten.
# https://bugs.launchpad.net/puppet-cinder/+bug/1598094
- id: solidfire_cinder
  type: puppet
  version: 3.0.0
  groups: [cinder]
  requires: [top-role-cinder]
  required_for: [deploy_end]
  condition:
    yaql_exp: >
      changedAny($.cinder_solidfire, $.cinder, $.get('cinder_volume_group'),
      $.network_metadata.nodes.get(concat("node-", $.uid)).network_roles.get('cinder/iscsi'),
      $.network_metadata.vips, $.debug, $.node_volumes, $.storage, $.rabbit, $.ceilometer,
      $.get('use_stderr'), $.get('use_syslog'), $.get('syslog_log_facility_cinder'),
      $.get('syslog_log_facility_ceph'), $.get('proxy_port'), $.get('kombu_compression'),
      $.get('use_ssl'), $.get('service_endpoint'), $.get('glance_api_servers'),
      $.get('amqp_hosts'),
      $.network_metadata.nodes.values().where(
        $.node_roles.any($.matches('controller'))).network_roles.select(
          $.get('mgmt/messaging')))
  parameters:
    puppet_manifest: puppet/manifests/site.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 360
