attributes:
  multibackend:
    value: true
    label: 'Multibackend enabled'
    description: 'SolidFire will be used in a Multibackend env.'
    weight: 10
    type: "checkbox"
  solidfire_mvip:
    value: ''
    label: 'Cluster MVIP (san_ip)'
    description: 'The hostname (or IP address) for the SolidFire Cluster API endpoint.'
    weight: 20
    type: "text"
  solidfire_admin_login:
    value: ''
    label: 'Login for Cluster Admin account (san_login)'
    description: 'Cluster account used by Cinder service.'
    weight: 30
    type: "text"
    regex:
      source: '\S'
      error: "Username field cannot be empty"
  solidfire_admin_password:
    value: ''
    label: 'Password for Cluster Admin account (san_password)'
    description: 'Cluster account used by Cinder service.'
    weight: 40
    type: "password"
  solidfire_api_port:
    value: '443'
    label: 'Cluster endpoint port'
    description: 'The TCP port to use for API communication with the cluster or proxy server.'
    weight: 50
    type: "text"
  solidfire_allow_template_caching:
    value: true
    label: 'Enable Caching'
    description: 'When creating bootable volumes, create an image cache on the SolidFire cluster.'
    weight: 51
    type: "checkbox"
  solidfire_template_account:
    value: 'openstack-vtemplate'
    label: 'Template Account'
    description: 'SolidFire account to use to hold the template cache.'
    weight: 52
    type: "text"
  solidfire_emulate_512:
    value: "true"
    values:
        - data: "true"
          label: "True"
          description: "Enables 512 byte emulation on volumes during creation."
        - data: "false"
          label: "False"
          description: "Disables 512 byte emulation and uses the native 4096 byte block size."
    label: "SolidFire Emulate 512 block size"
    description: 'Enable/Disable 512 byte block size emulation (typically left enabled).'
    weight: 60
    type: "radio"
  solidfire_account_prefix:
    value: ''
    label: 'SF account prefix'
    description: 'Prefix to use for all SolidFire accounts related to this OpenStack.'
    weight: 70
    type: "text"
